[package]
name = "openapi-gen"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]

[build-dependencies]
sandbox-daemon = { path = "../sandbox-daemon" }
serde_json = "1.0"
utoipa = "4.2"
